### ISSUE TITLE
v1: todo

### ISSUE THREAD

**Issue by mengrru** [mengrru/hut#1]
- [ ] design plugin & theme spec
- [ ] implement plugins loader
- [ ] migrate / reimplement all existing plugins
- [ ] migrate some themes
- [ ] CI/CD
- [ ] documentation
